export const Projects = [
  {
    title: "Weather App",
    tags: "react",
    description: "Application weather",
    urlCode: "#",
    urlDemo: "#",
    image: "src/assets/project-weather.png",
  },
  {
    title: "Country Quiz",
    tags: "react",
    description: "Application",
    urlCode: "https://github.com/ghizlane-elatmani/Country-quiz",
    urlDemo: "#",
    image: "src/assets/project-quiz.png",
  },
  {
    title: "Todo",
    tags: "react",
    description: "Application",
    urlCode: "https://github.com/ghizlane-elatmani/Todo-App",
    urlDemo: "https://todo-app-ge.netlify.app/",
    image: "src/assets/project-todo.png",
  },
  {
    title: "WindBnb",
    tags: "react",
    description: "Application",
    urlCode: "https://github.com/ghizlane-elatmani/Windbnb",
    urlDemo: "https://windbnb-ge.netlify.app/",
    image: "src/assets/project-windbnb.png",
  },
  {
    title: "Edie homepage",
    tags: "responsive",
    description: "Application",
    urlCode: "https://github.com/ghizlane-elatmani/Edie-homepage",
    urlDemo: "https://edie-homepage-ge.netlify.app/",
    image: "src/assets/project-edie.png",
  },
  {
    title: "Checkout Page",
    tags: "responsive",
    description: "Application",
    urlCode: "https://github.com/ghizlane-elatmani/Checkout-Page",
    urlDemo: "https://checkout-page-ge.netlify.app/",
    image: "src/assets/project-checkout.png",
  },

  {
    title: "Recipe Blog",
    tags: "responsive",
    description: "Application",
    urlCode: "https://github.com/ghizlane-elatmani/Recipe-Page",
    urlDemo: "https://recipe-blog-ge.netlify.app/",
    image: "src/assets/project-recipe.png",
  },
];
