export const Projects = [
  {
    title: "Weather App",
    tags: "react",
    description: "Application weather",
    urlCode: "#",
    urlDemo: "#",
    image: "src/assets/project-weather.png",
  },
  {
    title: "Country Quiz",
    tags: "react",
    description: "Application",
    urlCode: "#",
    urlDemo: "#",
    image: "src/assets/project-quiz.png",
  },
  {
    title: "Todo",
    tags: "react",
    description: "Application",
    urlCode: "#",
    urlDemo: "#",
    image: "src/assets/project-todo.png",
  },
  {
    title: "WindBnb",
    tags: "react",
    description: "Application",
    urlCode: "#",
    urlDemo: "#",
    image: "src/assets/project-windbnb.png",
  },
  {
    title: "Edie homepage",
    tags: "responsive",
    description: "Application",
    urlCode: "#",
    urlDemo: "#",
    image: "src/assets/project-edie.png",
  },
  {
    title: "Checkout Page",
    tags: "responsive",
    description: "Application",
    urlCode: "#",
    urlDemo: "#",
    image: "src/assets/project-checkout.png",
  },

  {
    title: "Recipe Blog",
    tags: "responsive",
    description: "Application",
    urlCode: "#",
    urlDemo: "#",
    image: "src/assets/project-recipe.png",
  },
];
