export const Projects = [
  // {
  //   title: "Weather App",
  //   name: "project-weather",
  //   tags: "react",
  //   description: "Application weather",
  //   urlCode: "#",
  //   urlDemo: "#",
  // },
  {
    title: "Country Quiz",
    name: "project-quiz",
    tags: "react",
    description: "Application",
    urlCode: "https://github.com/ghizlane-elatmani/Country-quiz",
    urlDemo: "#",
  },
  {
    title: "Todo",
    name: "project-todo",
    tags: "react",
    description: "Application",
    urlCode: "https://github.com/ghizlane-elatmani/Todo-App",
    urlDemo: "https://todo-app-ge.netlify.app/",
  },
  {
    title: "WindBnb",
    name: "project-windbnb",
    tags: "react",
    description: "Application",
    urlCode: "https://github.com/ghizlane-elatmani/Windbnb",
    urlDemo: "https://windbnb-ge.netlify.app/",
  },
  {
    title: "Edie homepage",
    name: "project-edie",
    tags: "responsive",
    description: "Application",
    urlCode: "https://github.com/ghizlane-elatmani/Edie-homepage",
    urlDemo: "https://edie-homepage-ge.netlify.app/",
  },
  {
    title: "Checkout Page",
    name: "project-checkout",
    tags: "responsive",
    description: "Application",
    urlCode: "https://github.com/ghizlane-elatmani/Checkout-Page",
    urlDemo: "https://checkout-page-ge.netlify.app/",
  },

  {
    title: "Recipe Blog",
    name: "project-recipe",
    tags: "responsive",
    description: "Application",
    urlCode: "https://github.com/ghizlane-elatmani/Recipe-Page",
    urlDemo: "https://recipe-blog-ge.netlify.app/",
  },
];
